export { default as OrdersModule } from './OrdersModule'
export { default as SidebarModule } from './SidebarModule'
export { default as SettingsModule } from './SettingsModule'
export { default as ConsultationModule } from './ConsultationModule'
export { default as PaymentMethodsModule } from './PaymentMethodsModule'
