import type { Metadata } from "next";
import { FC, ReactNode } from "react";
import { Inter } from "next/font/google";
import Link from "next/link";
import { Dropdown } from "@/components";
import { AvatarIcon, FlagUzIcon, LocationIcon } from "@/assets/icons";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface IProps {
  children: ReactNode;
}

const RootLayout: FC<IProps> = ({ children }) => {
  const titles = [
    { text: `Mahsulotlar katalogi`, href: `#` },
    { text: `Foto-lavhalar`, href: `#` },
    { text: `Yetkazib berish va to'lash`, href: `#` },
    { text: `Aksiya`, href: `#`, color: `#AB7A19` },
    { text: `Yangi`, href: `#`, color: `#53B175` },
  ];

  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <nav className="flex items-center justify-between bg-green-light h-10 px-24 text-sm">
            <ul className="flex gap-5">
              {titles.map(({ text, href }) => (
                <Link href={href} key={text}>
                  {text}
                </Link>
              ))}
            </ul>
            <ul className="flex items-center gap-5">
              <div>
                <Dropdown
                  items={[
                    {
                      label: (
                        <div className="flex items-center">
                          <span>
                            <FlagUzIcon />
                          </span>
                          <span>Uzbek</span>
                        </div>
                      ),
                      id: "uz",
                      selected: true,
                    },
                  ]}
                  // onClick={() => {}}
                />
              </div>
              <div className="flex items-center gap-2">
                <div>Toshkent shahar</div>
                <div>
                  <LocationIcon />
                </div>
              </div>
              <div className="flex items-center gap-2">
                <div>Kirish</div>
                <div>
                  <AvatarIcon />
                </div>
              </div>
            </ul>
          </nav>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
};

export default RootLayout;
